var config = {
    style:'mapbox://styles/croissant-cheungx/cm4dqodt400h601rwht4e3e08',
    accessToken: 'pk.eyJ1IjoiY3JvaXNzYW50LWNoZXVuZ3giLCJhIjoiY20xdGk1MnJvMDJvcjJrcTgxZXZ6em4wOCJ9.5aHf_tnCdC3gA9WMiCeYTw',
    showMarkers: false,
    markerColor: '#7400b8',
    //projection: 'equirectangular',
    //Read more about available projections here
    //https://docs.mapbox.com/mapbox-gl-js/example/projections/
    inset: false,
    theme: 'light',
    use3dTerrain: false, //set true for enabling 3D maps.
    title: 'Spatial Justice: EV Charging Station Equity in Onondaga County',
    subtitle: 'Assessing the equity of charging station distribution in Onondaga County, revealing possible service gaps and recommendations',
    byline: 'Kristi Zhang',
    para1: "Electric vehicle (EV) charging stations are critical for building a sustainable and fair transportation system. As EV adoption grows, ensuring charging infrastructure is accessible to all communities, especially underserved and low-income areas, is more important than ever.  The existing disparities in transportation and infrastructure access might leave suburban groups behind. Onondaga County, New York, with its diverse demographic and economic characteristics, offers an ideal setting to examine these challenges and highlight areas of inequity.",
    para2: "This project focuses on analyzing the distribution of EV charging stations in Onondaga County to identify service gaps and underserved areas. By using spatial analysis, it aims to clarify how current infrastructure placement aligns—or fails to align—with the needs of different communities. The findings will provide a clearer picture of where disparities exist, offering a critical foundation for future research and equitable infrastructure planning efforts.",
    footer: 'Source: Social Explorer, U.S. Department of Energy, CUGIR, Aregis Online, etc. <br> Created using <a href="https://github.com/iamwfx/crs_3850_5850_mapping_countermapping/tree/main/Week12_mon_storymaps/story_starterfiles" target="_blank">Mapbox Storytelling</a> template.',
    chapters: [
        {
            id: 'layer1 locations and buffer',
            alignment: 'left',
            hidden: false,
            title: 'Curretn EV Charging Station Locations',
            image: 'https://sonaenergy.com/wp-content/uploads/2022/03/ElectrifyAmerica-768x512.webp',
            imagedescription:'',
            description: '',
            location: {
                center: [-76.19468, 43.04721],
                zoom: 10.5,
                pitch: 0,
                bearing: 0,
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                 {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.4,},
                  {layer: 'populationonondaga',
                    opacity: 0,},
                  {layer: 'medianhouseholdincome',
                    opacity: 0,},
                  {layer: 'housingunits',
                    opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.3,},
                  {layer: 'populationonondaga',
                    opacity: 0,},
                  {layer: 'medianhouseholdincome',
                    opacity: 0.5,},
                  {layer: 'housingunits',
                    opacity: 0,},
            ]
        },
        {
            id: 'layer2 medianhouseholdincome',
            alignment: 'right',
            hidden: false,
            title: 'Income Disparities and EV Infrastructure Accessibility',
            image: 'https://files.americanexperiment.org/wp-content/uploads/2018/05/Wealthy-Electric-Car-owners.png',
            imagedescription:'',
            description: 'Median household income is one of the most important indicators for assessing the accessibility of electric vehicle infrastructure. By analyzing the relationship between income level and the distribution of charging stations, we can identify communities that may face underserved services. This map uses a three-mile buffer analysis to show coverage in lower-income areas, aiming to support addressing possible inequalities in the distribution of charging stations.',
            location: {
                center: [-76.12070, 43.05418],
                zoom: 10,
                pitch: 0,
                bearing: 0,
            },
            mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.3,},
                  {layer: 'populationonondaga',
                    opacity: 0,},
                  {layer: 'medianhouseholdincome',
                    opacity: 0.6,},
                  {layer: 'housingunits',
                    opacity: 0,},
                 
            ],
            onChapterExit: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0,},
                  
                  {layer: 'medianhouseholdincome',
                    opacity: 0,},
                  {layer: 'housingunits',
                    opacity: 0,},
            ]
        },
        {
        id: 'population',
        alignment: 'right',
        hidden: false,
        title: 'Population Density and Service Equity',
        description: 'Population density determines, to a certain extent, the level of demand for electric vehicle charging stations in a community. By analyzing the overlap between population distribution and charging station locations, we can assess whether high-density areas have received adequate service support and further optimize infrastructure layout.',
        image:'https://www.researchgate.net/profile/Ahmed-Wefky/publication/240164934/figure/fig1/AS:669417901932550@1536613073125/GROWTH-OF-POPULATION-AND-VEHICLES-The-prevalence-of-electric-automobiles-in-vehicle.png',
        imagedescription:'',
        location: {
        center: [-76.19193, 43.02385],
        zoom: 10.7,
        pitch: 40,
        bearing: 50,
        mapAnimation: 'flyTo',
            rotateAnimation: false,
            callback: '',
            onChapterEnter: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.4,},
                  {layer: 'populationonondaga',
                    opacity: 0.8,
                    },
                  {layer: 'medianhouseholdincome',
                    opacity: 0,},
                  {layer: 'housingunits',
                    opacity: 0,},
            ],
            onChapterExit: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.2,},
                  {layer: 'populationonondaga',
                    opacity: 1,},
                  {layer: 'medianhouseholdincome',
                    opacity: 0,},
                  {layer: 'housingunits',
                    opacity: 0.3,},
            ]
        },
    },
        {
            id: 'housingunits',
            alignment: 'right',
            hidden: false,
            title: 'Housing Units and Charging Needs',
            image: 'https://plan.ongov.net/wp-content/uploads/2024/08/Housing_Chart.png',
            imagedescription:'Image retrived from <a href="https://plan.ongov.net/housing-onondaga/" target="_blank">Housing Onondaga</a>',
            description:'The total number of housing units in a community directly influences the demand for EV charging infrastructure to a certain degree. Areas with a high concentration of housing units typically require more charging stations to meet the needs of residents, especially in densely populated neighborhoods. High housing unit counts often correlate with increased vehicle ownership, enlarging the pressure on existing public charging infrastructure. Conversely, areas with fewer housing units, such as very rural or suburban neighborhoods, may exhibit lower demand but still require strategic placement of chargers to ensure accessibility. Understanding the distribution and quantity of housing units is essential for identifying potential service gaps and planning equitable deployment of EV charging stations. <img src="https://plan.ongov.net/wp-content/uploads/2024/08/Housing_Chart.png><small>Test Citation</small>',
            location: {
                center: [-76.12136, 43.02550],
                zoom: 10.5,
                pitch: 45,
                bearing: 30,
                speed: 0.4, 
                curve: 1,
                // flyTo additional controls-
                // These options control the flight curve, making it move
                // slowly and zoom out almost completely before starting
                // to pan.
                //speed: 2, // make the flying slow
                //curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: true,
            callback: '',
            onChapterEnter: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.4,},
                  {layer: 'populationonondaga',
                    opacity: 0,},
                  {layer: 'medianhouseholdincome',
                    opacity: 0,},
                  {layer: 'housingunits',
                    opacity: 0.8,},
                ],
            onChapterExit: []
        },
        {
            id: 'housingtypes',
            alignment: 'right',
            hidden: false,
            title: 'Housing Types and Charging Needs',
            image: 'https://images.surferseo.art/8a0c1c28-fe0d-4160-92e0-43126bfae7b1.png',
            imagedescription:'',
            description:'Based on research and interviews, housing unit types directly influence the demand for public EV charging stations. Residents in single-family houses often have the convenience of private charging facilities, typically located in their own garages, offering flexibility and easy to use. In contrast, residents of multi-family housing units and apartment renters rely heavily on public charging infrastructure due to the lack of private charging options. This disparity highlights the unique challenges faced by different types of housing and reveals the importance of understanding these needs when evaluating existing EV charging infrastructure.',
            location: {
                center: [-76.11553, 43.13513],
                zoom: 10,
                pitch: 45,
                bearing: 30,
                speed: 0.8, 
                curve: 1,
                // flyTo additional controls-
                // These options control the flight curve, making it move
                // slowly and zoom out almost completely before starting
                // to pan.
                //speed: 2, // make the flying slow
                //curve: 1, // change the speed at which it zooms out
            },
            mapAnimation: 'flyTo',
            rotateAnimation: true,
            callback: '',
            onChapterEnter: [
                {layer: 'ev-charging-stations-onondaga-b0ubaz',
                    opacity: 1,
                    duration: 5000},
                  {layer: '3-mile-buffer-319zps',
                    opacity: 0.4,},
                  {layer: 'populationonondaga',
                    opacity: 0,},
                  {layer: 'medianhouseholdincome',
                    opacity: 0,},
                  {layer: 'housingunits',
                    opacity: 0.6,},
                ],
            onChapterExit: []
        },
        
    ]
};
